system_config:
 - resolve_conf:
   - write_file:
     - /etc/resolv.conf
     - |
       nameserver 208.67.222.222
       nameserver 208.67.220.220
 - fstab:
   - write_file:
     - /etc/fstab
     - |
       devpts /dev/pts devpts gid=5,mode=620 0 0
       tmpfs  /dev/shm tmpfs  defaults       0 0
       proc   /proc    proc   defaults       0 0
       sysfs  /sys     sysfs  defaults       0 0
 - etc_hosts:
   - write_file:
     - /etc/hosts
     - |
       127.0.0.1  localhost oar
 - etc_hostname:
   - write_file:
     - /etc/sysconfig/network
     - |
       NETWORKING=yes
       NETWORKING_IPV6=NO
       HOSTNAME=oar
 - network_interfaces:
   - write_file:
     - /etc/sysconfig/network-scripts/ifcfg-eth0
     - |
       DEVICE=eth0
       BOOTPROTO=DHCP
       ONBOOT=on
   - exec_chroot: /sbin/chkconfig --level 35 network on
 - yum:
   - write_file:
     - /etc/yum.conf
     - |
       [main]
       cachedir=/var/cache/yum
       debuglevel=1
       reposdir=/dev/null
       logfile=/var/log/yum.log
       retries=20
       obsoletes=1
       gpgcheck=0
       assumeyes=1
       
       # repos
       
       [core]
       name=core
       baseurl=http://download.fedora.redhat.com/pub/fedora/linux/releases/10/Fedora/$$arch/os/
   - exec_chroot: yum update
   - exec_chroot: yum install glibc-common
 - adduser:
   - exec_chroot: yum install authconfig
   - exec_chroot: authconfig --enableshadow --update
   - exec_chroot: useradd -m -p '$1$f/W7v.Ze$LMPAjbXywS/f1dHzrmXpg/' -s /bin/bash kameleon
 - sudo:
   - exec_chroot: yum install sudo
   - append_file:
     - /etc/sudoers
     - |
       %wheel ALL=(ALL) NOPASSWD: ALL
   - exec_chroot: usermod -G wheel kameleon
 - selinux:
   - exec_chroot: mkdir -p /etc/selinux || true
   - write_file:
     - /etc/selinux/config
     - |
       SELINUX=disabled
