oar_config:
 - config_mysql:
   - exec_chroot: /etc/init.d/mysql start || service mysql start || true
   - exec_chroot: mysqladmin password kameleon
   - exec_on_clean: chroot $$chroot bash -c "/etc/init.d/mysql stop || service mysql stop || true"
 - config_taktuk:
   - exec_chroot: mv /etc/oar/oar.conf /etc/oar/oar.conf.or
   - exec_chroot: sed -e 's/^#\(TAKTUK_CMD\=\"\/usr\/bin\/taktuk \-t 30 \-s\".*\)/\1/' /etc/oar/oar.conf.or > $$chroot/etc/oar/oar.conf.tmp
   - exec_chroot: sed -e 's/^#\(PINGCHECKER_TAKTUK_ARG_COMMAND\=\"broadcast exec timeout 5 kill 9 \[ true \]\".*\)/\1/' /etc/oar/oar.conf.tmp > $$chroot/etc/oar/oar.conf
 - config_oar_log_level:
   - exec_chroot: mv /etc/oar/oar.conf /etc/oar/oar.conf.or
   - exec_chroot: sed -e 's/^LOG_LEVEL\=\"2\"/LOG_LEVEL\=\"3\"/' /etc/oar/oar.conf.or > $$chroot/etc/oar/oar.conf
 - config_cpuset:
   - exec_chroot: mv /etc/oar/oar.conf /etc/oar/oar.conf.tmp
   - exec_chroot: sed -e 's/^#\(JOB_RESOURCE_MANAGER_PROPERTY_DB_FIELD\=\"cpuset\".*\)/\1/' /etc/oar/oar.conf.tmp > $$chroot/etc/oar/oar.conf
   - exec_chroot: mv /etc/oar/oar.conf /etc/oar/oar.conf.tmp
   - exec_chroot: sed -e 's/^#\(JOB_RESOURCE_MANAGER_FILE\=\"\/etc\/oar\/job_resource_manager\.pl\".*\)/\1/' /etc/oar/oar.conf.tmp > $$chroot/etc/oar/oar.conf
#   - exec_chroot: mv /etc/oar/oar.conf /etc/oar/oar.conf.tmp
#   - exec_chroot: sed -e 's/^DB_BASE_PASSWD\=\"\"/DB_BASE_PASSWD\=\"kameleon\"/' /etc/oar/oar.conf.tmp > $$chroot/etc/oar/oar.conf
   - exec_chroot: mv /etc/oar/oar.conf /etc/oar/oar.conf.tmp
   - exec_chroot: sed -e 's/^#\(CPUSET_PATH\=\"\/oar\".*\)/\1/' /etc/oar/oar.conf.tmp > $$chroot/etc/oar/oar.conf
   - exec_chroot: perl -pi -e 's/^DETACH_JOB_FROM_SERVER="0"/DETACH_JOB_FROM_SERVER="1"/' /etc/oar/oar.conf
   - exec_chroot: perl -pi -e 's/^ssh-/environment="OAR_KEY=1" ssh-/' /var/lib/oar/.ssh/authorized_keys
 - oar_init:
   - exec_chroot: oar-database --create --db-admin-user root --db-admin-pass kameleon --db-ro-user oar_ro --db-ro-pass oar_ro
 - update_hostfile:
   - append_file:
     - /etc/hosts
     - |
       127.0.0.2 node1 node2
 - hosts_check_startup:
   - append_file: 
     - /etc/default/oar-server
     - |
       cat /etc/hosts | grep node1 2>/dev/null|| echo '127.0.0.2 node1 node2' >> /etc/hosts
 - add_properties:
   - exec_chroot: oarproperty -a core
   - exec_chroot: oarproperty -a cpu
 - create_resources:
   - exec_chroot: oarnodesetting -a -h node1 -p cpu=0 -p core=0 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h node1 -p cpu=0 -p core=1 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h node1 -p cpu=1 -p core=2 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h node1 -p cpu=1 -p core=3 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h node2 -p cpu=2 -p core=4 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h node2 -p cpu=2 -p core=5 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h node2 -p cpu=3 -p core=6 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h node2 -p cpu=3 -p core=7 -p cpuset=0
 - modify_job_resource_manager:
   - exec_chroot: mv /etc/oar/job_resource_manager.pl /etc/oar/job_resource_manager.pl.tmp
   - exec_chroot: sed -e 's/#exit/exit/' /etc/oar/job_resource_manager.pl.tmp > $$chroot/etc/oar/job_resource_manager.pl


