oar_config:
 - config_mysql:
   - exec_chroot: /etc/init.d/mysql start || service mysql start || true
   - exec_chroot: echo "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('kameleon')" | chroot $$chroot mysql --user=root
 - config_taktuk:
   - exec_chroot: mv /etc/oar/oar.conf /etc/oar/oar.conf.or
   - exec_chroot: sed -e 's/^#\(TAKTUK_CMD\=\"\/usr\/bin\/taktuk \-t 30 \-s\".*\)/\1/' /etc/oar/oar.conf.or > $$chroot/etc/oar/oar.conf.tmp
   - exec_chroot: sed -e 's/^#\(PINGCHECKER_TAKTUK_ARG_COMMAND\=\"broadcast exec timeout 5 kill 9 \[ true \]\".*\)/\1/' /etc/oar/oar.conf.tmp > $$chroot/etc/oar/oar.conf
 - config_cpuset:
   - exec_chroot: mv /etc/oar/oar.conf /etc/oar/oar.conf.tmp
   - exec_chroot: sed -e 's/^#\(JOB_RESOURCE_MANAGER_PROPERTY_DB_FIELD\=\"cpuset\".*\)/\1/' /etc/oar/oar.conf.tmp > $$chroot/etc/oar/oar.conf
   - exec_chroot: mv /etc/oar/oar.conf /etc/oar/oar.conf.tmp
   - exec_chroot: sed -e 's/^#\(JOB_RESOURCE_MANAGER_FILE\=\"\/etc\/oar\/job_resource_manager\.pl\".*\)/\1/' /etc/oar/oar.conf.tmp > $$chroot/etc/oar/oar.conf
   - exec_chroot: mv /etc/oar/oar.conf /etc/oar/oar.conf.tmp
   - exec_chroot: sed -e 's/^#\(CPUSET_PATH\=\"\/oar\".*\)/\1/' /etc/oar/oar.conf.tmp > $$chroot/etc/oar/oar.conf
   - exec_chroot: perl -pi -e 's/^ssh-/environment="OAR_KEY=1" ssh-/' /var/lib/oar/.ssh/authorized_keys
 - oar_init:
   - write_file:
     - /usr/lib/oar/init.sql
     - |
       CREATE DATABASE IF NOT EXISTS oar;

       CONNECT mysql;
       INSERT INTO user (Host,User,Password) VALUES('localhost','oar',PASSWORD('oar'));

       INSERT INTO user (Host,User,Password) VALUES('%','oar',PASSWORD('oar'));
       INSERT INTO db  (Host,Db,User,Select_priv,Insert_priv,Update_priv,Delete_priv, Create_priv,Drop_priv) VALUES ('localhost','oar','oar','Y','Y','Y','Y','Y','Y');
       INSERT INTO db  (Host,Db,User,Select_priv,Insert_priv,Update_priv,Delete_priv, Create_priv,Drop_priv) VALUES ('%','oar','oar','Y','Y','Y','Y','Y','Y');
       FLUSH PRIVILEGES;

       GRANT ALL ON oar.* TO oar@localhost;
       GRANT ALL ON oar.* TO oar@'%';
       GRANT SELECT ON oar.* TO oarreader@localhost;
       GRANT SELECT ON oar.* TO oarreader@'%';
       FLUSH PRIVILEGES;
   - exec_chroot: mysql -u root -p"kameleon" < $$chroot/usr/lib/oar/init.sql
   - exec_chroot: mysql -u root -p"kameleon" oar < $$chroot/usr/lib/oar/mysql_structure.sql
   - exec_chroot: mysql -u root -p"kameleon" oar < $$chroot/usr/lib/oar/mysql_default_admission_rules.sql
   - exec_chroot: mysql -u root -p"kameleon" oar < $$chroot/usr/lib/oar/default_data.sql || true
 - update_hostfile:
   - append_file:
     - /etc/hosts
     - |
       127.0.0.2 node1 node2
 - create_resources:
   - exec_chroot: oarproperty -a core
   - exec_chroot: oarproperty -a cpu
   - exec_chroot: oarnodesetting -a -h node1 -p cpu=0 =p core=0
   - exec_chroot: oarnodesetting -a -h node1 -p cpu=0 =p core=1
   - exec_chroot: oarnodesetting -a -h node1 -p cpu=1 =p core=0
   - exec_chroot: oarnodesetting -a -h node1 -p cpu=1 =p core=1
   - exec_chroot: oarnodesetting -a -h node2 -p cpu=0 =p core=0
   - exec_chroot: oarnodesetting -a -h node2 -p cpu=0 =p core=1
   - exec_chroot: oarnodesetting -a -h node2 -p cpu=1 =p core=0
   - exec_chroot: oarnodesetting -a -h node2 -p cpu=1 =p core=1
