g5k-ldap-config:
 - install_ldap_packages:
   - exec_chroot: bash -c "DEBIAN_FRONTEND=noninteractive apt-get update"
   - exec_chroot: bash -c "DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes install libnss-ldap libpam-ldap nscd"
 - write_libnss-ldap.conf:
   - exec_current: cp $$include_dir/etc/libnss-ldap.conf  $$chroot/etc/
 - write_pam_ldap.conf:
   - exec_current: cp $$include_dir/etc/pam_ldap.conf  $$chroot/etc/
 - write_ldap.conf:
   - exec_current: mkdir $$chroot/etc/ldap || true
   - exec_current: cp $$include_dir/etc/ldap/ldap.conf  $$chroot/etc/ldap
 - write_nsswitch.conf:
   - exec_current: cp $$include_dir/etc/nsswitch.conf  $$chroot/etc/

