network_config_static:
 - interfaces:
   - write_file:
     - /etc/network/interfaces
     - |
       auto lo
       iface lo inet loopback

       auto eth0
       iface eth0 inet static
         address $$network_eth0_ip
         netmask $$network_eth0_mask
         gateway $$network_gateway
 - resolv_conf:
   - write_file:
     - /etc/resolv.conf
     - |
       search $$network_domain
       nameserver $$network_dns

