system_config:
 - fstab:
   - write_file:
     - /etc/fstab
     - |
       proc /proc proc defaults 0 0
 - etc_hosts:
   - write_file:
     - /etc/hosts
     - |
       127.0.0.1  localhost $$network_hostname
 - etc_hostname:
   - write_file:
     - /etc/hostname
     - |
       $$network_hostname
 - network_interfaces:
   - write_file:
     - /etc/sysconfig/network-scripts/ifcfg-eth0
     - |
       DEVICE=eth0
       BOOTPROTO=dhcp
       ONBOOT=yes
